services:
  database:
    container_name: database
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: mon_zoo
      MYSQL_USER: adminJose
      MYSQL_PASSWORD: adminJosePwd
    ports:
      - '4306:3306'
    volumes:
      - ./mysql:/var/lib/mysql
    restart: always
  php:
    container_name: php
    build:
      context: ./app
    ports:
      - "8080:80"
      - "8443:443"
    restart: always
    volumes:
      - ./apache/default.conf:/etc/apache2/sites-enabled/000-default.conf
      - ./apache/default-ssl.conf:/etc/apache2/sites-enabled/000-default-ssl.conf
      - ./etc/ssl:/etc/ssl
    depends_on:
      - database
      - mongo

  mailhog:
    image: mailhog/mailhog
    logging:
      driver: 'none'
    ports:
      - 1025:1025 #SMTP
      - 8025:8025 #Boite mail
  mongo:
    image: mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - ./mongodb:/data/db
    restart: always
