framework:
    asset_mapper:
        enabled: true
        # The paths to make available to the asset mapper.
        paths:
            - assets/
# framework:
#     assets:
#         enabled: true
#         base_path: '/public'